Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "fast-lab-vm"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "lab-vm"
        vb.memory = 2048
        vb.cpus = 2
    end
end