Vagrant.configure("2") do |config| # abre o bloco de configuração do Vagrant
  # Configuração do Vagrant
  config.vm.box = "ubuntu/jammy64"

  bridge_iface   = "Realtek PCIe GbE Family Controller" # Interface de rede bridged
  # Pode ser necessário ajustar o nome da interface de rede conforme o sistema operacional
  default_memory = 2048 # Memória padrão para as VMs
  default_cpu    = 2 # Número padrão de CPUs para as VMs

  vms = [
    {
      name: "vm1", # Nome da VM
      hostname: "fast-lab-vm1", # Nome do host da VM
      ip: "192.168.0.120",
      vb_name: "lab-vm1", # Nome da VM no VirtualBox
      # memory: 3096,
      # cpu: 3
    },
    {
      name: "vm2",
      hostname: "fast-lab-vm2",
      ip: "192.168.0.121",
      vb_name: "lab-vm2",
    }
  ]

  vms.each do |vm_conf|
    config.vm.define vm_conf[:name] do |vm|
      vm.vm.hostname = vm_conf[:hostname]
      vm.vm.network "public_network", bridge: bridge_iface, ip: vm_conf[:ip]

      vm.vm.provider "virtualbox" do |vb|
        vb.name   = vm_conf[:vb_name]
        vb.memory = vm_conf.fetch(:memory, default_memory)
        vb.cpus   = vm_conf.fetch(:cpu,    default_cpu)
      end

      vm.vm.synced_folder "../praticas", "/home/vagrant/app", owner: "vagrant", group: "vagrant"

      if vm_conf[:name] == "vm1"
        vm.vm.provision "shell", privileged: true, path: "provision/nginx.sh", run: "once"
      else
        vm.vm.provision "docker", run: "always" do |d|
          d.run "nginx", image: "nginx:latest", args: "-p 80:80", restart: "always"
        end
        vm.vm.provision "shell", inline: "usermod -aG docker vagrant || true"
      end
    end
  end
end
